import type { Metadata } from "next";
import "./globals.css";
// import NavBar from "../components/nav-bar";
import { geistSans, geistMono, dmMono } from "./fonts";
import NavBar from "@/components/nav-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmMono.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
